/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'grant' at '5/3/17 9:51 PM' with Gradle 2.13
 *
 * @author grant, @date 5/3/17 9:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
